### ISSUE TITLE
We don't need to require six anymore

### ISSUE THREAD

**Issue by PierreSelim** [Commonists/MediaCollectionDB#6]
Since v0.7.2 of mwclient, mwclient correctly requires six https://github.com/mwclient/mwclient/commit/c9ea5e6d3227a267c11c624f2f09dfbcb0a17ea1 

I think we can remove this dependency, can we @JeanFred ?

**Comment by JeanFred** [comment]
I think it is, yes @PierreSelim. I tried testing it − removing six, pinning mwclient at 0.7.1 and running tox, but not failure. Our test coverage is probably not good enough :)
